apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  env:
    - name: TZ
      value: 'Asia/Taipei'
  deploymentPlan:
    size: 1
    enableMetricsPlugin: true
    image: placeholder
    messageMigration: true
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "250m"
        memory: "512Mi"
  acceptors:
    - name: all-acceptors
      protocols: all
      port: 61616
      connectionsAllowed: 100
  console: 
    expose: true