kind: Deployment
apiVersion: apps/v1
metadata:
  name:  helloworld-mdb
  labels:
    app:  helloworld-mdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  helloworld-mdb
  template:
    metadata:
      labels:
        app:  helloworld-mdb
    spec:
      containers:
      - name:  helloworld-mdb
        image: helloworld-mdb:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
        livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
        ports:
            - containerPort: 9990
              protocol: TCP
            - containerPort: 8080
              protocol: TCP     
        env: 
        - name: TZ
          value: 'Asia/Taipei'    
        - name: JAVA_OPTS
          value: >-
                -Damq.broker.host=ex-aao-hdls-svc.activemq-artemis-operator
                -Xms1G -Xms1G -Xmx1536m
                -Djboss.modules.system.pkgs=org.jboss.byteman,com.manageengine 
                -Djava.util.logging.manager=org.jboss.logmanager.LogManager
                -Djboss.bind.address=0.0.0.0
                -Dwildfly.statistics-enabled=true
        resources:
          requests: 
            memory: 1Gi
            cpu: 500m
          limits: 
            memory: 1536Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-mdb
    service: helloworld-mdb
  name: helloworld-mdb
spec:
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: probe
    protocol: TCP
    port: 9990
    targetPort: 9990
  selector:
    app: helloworld-mdb
  sessionAffinity: None
  type: ClusterIP