{
 "title": "K8s_Logs_from_Loki -2023-0425-v1",
 "description": "Basic dashboard for Kubernetes Logs from Loki. You will need to make your own customizations.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "LOKI_DS", "query": "loki" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$ns\" } , pod)"
    }
   },
   {
    "name": "search",
    "label": "Search Term",
    "query": "error|fatal,warn|error|fatal,fatal,error,warn,info,.+"
   }
  ]
 },
 "panels": [
  {
   "title": "\"$search\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$ns\", pod=~\"$pod\"} |~ \"(?i)$search\")[$__interval])) * 100 / sum(count_over_time(({ namespace=~\"$ns\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$ns\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of \"$search\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$ns\", pod=~\"$pod\"} |~ \"(?i)$search\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$search\" historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$ns\", pod=~\"$pod\"} |~ \"(?i)$search\")[$__interval])) by (pod)"
    }
   ]
  },
  {
   "title": "\"$search\" Rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({namespace=~\"$ns\", pod=~\"$pod\"} |~ \"(?i)$search\")[$__interval])) by (pod)"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$ns\", pod=~\"$pod\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "\"$search\"  Log distributed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$ns\", pod=~\"$pod\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$search\" Logs Panel",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{namespace=~\"$ns\", pod=~\"$pod\"} |~ \"(?i)$search\""
    }
   ]
  }
 ]
}