kind: Deployment
apiVersion: apps/v1
metadata:
  name:  helloworld-anthos
  labels:
    app:  helloworld-anthos 
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  helloworld-anthos
  template:
    metadata:
      labels:
        app:  helloworld-anthos 
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name:  helloworld-anthos
        image: helloworld-anthos:latest  
        imagePullPolicy: IfNotPresent
        readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        ports:
            - containerPort: 9990
              protocol: TCP
            - containerPort: 8080
              protocol: TCP     
        env:
        - name: POSTGRESQL_SERVICE_HOST
          value: "postgresql-database-service.database.svc.cluster.local"
        - name: POSTGRESQL_SERVICE_PORT
          value: "5432"
        - name: POSTGRESQL_USER
          value: "todos"
        - name: POSTGRESQL_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRESQL_DATASOURCE
          value: "WeatherDS"
        - name: POSTGRESQL_DATABASE 
          value: "todos" 
        - name: POSTGRESQL_URL 
          value: "jdbc:postgresql://${env.POSTGRESQL_SERVICE_HOST}:${env.POSTGRESQL_SERVICE_PORT}/${env.POSTGRESQL_DATABASE}"
        - name: POSTGRESQL_ENABLED 
          value: "true"                       
        - name: POSTGRESQL_VALIDATE_ON_MATCH 
          value: "false"
        - name: POSTGRESQL_BACKGROUND_VALIDATION 
          value: "true"          
        - name: POSTGRESQL_BACKGROUND_VALIDATION_MILLIS
          value: "60000"                    
        - name: POSTGRESQL_FLUSH_STRATEGY
          value: "IdleConnections" 
        - name: WILDFLY_TRACING_ENABLED
          value: "true"
        - name: TZ
          value: 'Asia/Taipei'          
        - name: JAVA_OPTS
          value: >-
                -Dwildfly.statistics-enabled=true
                -Djboss.bind.address=0.0.0.0
                -Xms1G -Xms1G -Xmx1536m  
                -Djboss.modules.system.pkgs=org.jboss.byteman,com.manageengine 
                -Djava.util.logging.manager=org.jboss.logmanager.LogManager                
        resources:
          requests: 
            memory: 1Gi
            cpu: 500m
          limits: 
            memory: 1536Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-anthos
    service: helloworld-anthos
  name: helloworld-anthos
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: probe
    protocol: TCP
    port: 9990
    targetPort: 9990
  selector:
    app: helloworld-anthos
  sessionAffinity: None
  type: ClusterIP