name: wildfly-todo-backend images ci

on:
  push:
    paths:
      - 'wildfy-26.1.3.Final-sample-todo-backend/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8  
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./wildfy-26.1.3.Final-sample-todo-backend/
        run:  |
            echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
            mvn package
            docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/wildfly-todo-backend:latest .
            docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/wildfly-todo-backend:${{ steps.date.outputs.date }} .
            docker push ghcr.io/robert0714/wildfly-todo-backend:latest
            docker push ghcr.io/robert0714/wildfly-todo-backend:${{ steps.date.outputs.date }}